### ISSUE TITLE
No default level assigned when using Nextend Social Login

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-social-login#19]
**Describe the bug**
When assigning a default level for social logins a membership level is not assigned to the new user when logging in the first time with a social account through the Nextend Social Login plugin.

**To Reproduce**
1. Install and configure the Nextend Social Login plugin.
2. Navigate to Memberships > Settings > Levels, create a free level, and set it as the level to assign for social logins.
3. In a private browser window navigate to checkout for the free level and log in with a social account, e.g. Google,
4. After the social log is complete navigate to the Membership Account page and notice that no level was assigned.

**Expected behavior**
If a membership level is set for social logins users logging in or joining using social logins are given the set level.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WordPress 6.4.2 <br />
Paid Memberships Pro 2.12.8<br />
Nextend Social Login 3.1.11 <br />
PHP 7.4.33
</details>

**Comment by kimcoleman** [comment]
Adding this after line 127 of the main plugin file works - I can do a PR. So tough to test these things:

`add_action( 'nsl_register_new_user', 'pmprosl_pmpro_default_registration_level');`
